appearance:
  # Accent color, default '#2a2b33'
  accent_color:
  # Font color, default '#363636'
  foreground_color:
  # Border color, default '#e0e0e0'
  border_color:
  # body background, default '#f5f7fa'
  background:
  # Sidebar background (when opened), default to accent_color
  sidebar_background:
  # Card background, default '#fff'
  card_background:

  # All background settings above support image, e.g.,
  # '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa' or
  # 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # 内容区域最大宽度
  content_width: 640

  # 字体设置
  font:
    # 字体 CSS 文件的 URL
    url: //fonts.googleapis.com/css?family=Baloo+Bhaijaan|Inconsolata|Josefin+Sans|Montserrat

    # 基础字体，作用于 body 元素
    base: "'Josefin Sans', 'PingFang SC', Microsoft YaHei"
    # 作用于 sidebar 上方的 LOGO
    logo:
    # 作用于 sidebar 菜单栏
    menu: 'Baloo Bhaijaan'
    # 作用于文章百分比、归档页月份、分类文字数、分页、目录索引等地方
    label: Montserrat
    # 作用于标题
    heading:
    # 作用于代码及代码块
    code: Inconsolata, monospace
    # Base font for printing which applied to body
    print:

  # 代码语法高亮
  # 接受设置值为 16 个 hex 色值的数组，具体请参考 base16 (https://github.com/chriskempson/base16)
  # 默认配色方案为 Atelier Dune Light
  highlight: [
    '#ffffff', '#e0e0e0', '#d6d6d6', '#8e908c',
    '#969896', '#4d4d4c', '#282a2e', '#1d1f21',
    '#c82829', '#f5871f', '#eab700', '#718c00',
    '#3e999f', '#4271ae', '#8959a8', '#a3685a'
  ]

  # 启用 darkmode
  darkmode:
    accent_color: '#539bf5'
    foreground_color: '#adbac7'
    border_color: '#373e47'
    background: '#22272e'
    sidebar_background: '#22272e'
    card_background: '#2d333b'
    highlight: [
      '#2d333b', '#444c56', '#3e4451', '#545862',
      '#565c64', '#abb2bf', '#b6bdca', '#c8ccd4',
      '#e06c75', '#d19a66', '#e5c07b', '#98c379',
      '#56b6c2', '#61afef', '#c678dd', '#be5046'
    ]

# Sidebar profile
profile:
  # 邮箱用于生成 gravatar 头像，如配置了 `hexo.config.email`，此项可缺省
  email: d1zzzy.fe@gmail.com

  # 也可以直接设置头像 URL
  avatar: ./images/favicon.png

  # 个性签名
  bio: 一个玩飞盘的程序猿.

menu:
  主页: /
  关于: /about
  搜索: /search
  Github: https://github.com/d1zzzzy

footer:
  # 默认显示 @2019 • author，设置为 false 可隐藏。
  copyright: '&copy; 2023 ❤️ <a href="">凡生</a>'

  # `由 Hexo 强力驱动` 字样，默认显示，设置为 false 可隐藏。
  powered: false

  # `主题 - Inside` 字样，默认显示，设置为 false 可隐藏。
  theme: false

  # 于最后一行添加自定义内容
#  custom: Hosted by <a target="_blank" href="">Github Pages</a>

search:
  # 在页面右下角的 FAB 按钮里显示快捷搜索入口
  fab: true

  # 额外生成 search 页面，可配置在 sidebar 导航，如 `Search: /search`
  page: true

  # 以上两个入口必须至少设置一个，否则视为无效配置

  # 本地搜索，即生成本地 json 文件
  adapter:
    # json 数据的范围，数组
    range:
      - post
      - page

    # json 数据的条目限制
    # 假如 `limit:1000`，同时有 800 篇 post，800 篇 page，则最终生成的数据包含：
    # 800 篇 post，200 篇 page
    # 缺省值 `10000`
    limit: 10000

    # 搜索结果分页大小，缺省值 `10`
    per_page: 5

    # 用于统一数据格式，例如有如下返回结果
    # {
    #   "hits": [
    #     {
    #       "title": "Inside Theme Showcase",
    #       "date": "2018-09-05T06:28:24.000Z",
    #       "_snippetResult": {
    #         "title": { "value": "" },
    #         "content": { "value": "" }
    #       }
    #     }
    #   ],
    #   "nbHits": 10,
    #   "page": 0,
    #   "nbPages": 1,
    #   "processingTimeMS": 5
    # }
    # 则设置
    keys:
      data: hits
      current: page
      total: nbPage
      hits: nbHits
      time: processingTimeMS
      # title 对应具体某一条的标题字段
      title: _snippetResult.title.value
      # title 对应具体某一条的内容字段
      content: _snippetResult.content.value

comments: true

plugins:
  - //unpkg.com/valine/dist/Valine.min.js
  - position: comments
    template: |
      <div id="vcomment"></div>
      <script>
        new Valine({
          el: '#vcomment',
          appId: 'S5u48yL1AIT8PtF7n0hGIhb9-gzGzoHsz',
          appKey: 't52Ai5xcqqmT4DycALeMplLm',
          path: location.pathname
        })
      </script>
